### ISSUE TITLE
users_init error on managed PostgreSQL database (Oracle Cloud)

### ISSUE THREAD

**Issue by micgerber** [zebbra/data_aggregator#456]
Hi @hwuethrich,

I run [users_init](https://github.com/zebbra/data_aggregator/blob/main/docs/deployment.md#roll-out) and I got this error :

```
13:54:41.101 pid=<0.94.0> [error] could not import user: %{"email" => "dagi@infofauna.ch", "first_name" => "", "institution" => "", "last_name" => "", "password" => "Hm3&kE5f5?Bb", "roles" => "admin"}, reason was: %Ash.Error.Unknown{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: %ArgumentError{message: "unknown registry: DataAggregator.PubSub. Either the registry name is invalid or the registry is not running, possibly because its application isn't started"}, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}]}
** (throw) %Ash.Error.Unknown{changeset: "#Changeset<>",  errors: [%Ash.Error.Unknown.UnknownError{error: %ArgumentError{message: "unknown registry: DataAggregator.PubSub. Either the registry name is invalid or the registry is not running, possibly because its application isn't started"}, field: nil, value: nil, splode: Ash.Error, bread_crumbs: [], vars: [], path: [], stacktrace: #Splode.Stacktrace<>, class: :unknown}]}
    (data_aggregator 0.1.0) lib/data_aggregator/accounts/user_importer.ex:34: DataAggregator.Accounts.UserImporter.maybe_import_user_from_csv/1
    (elixir 1.17.2) lib/enum.ex:992: anonymous fn/3 in Enum.each/2
    (elixir 1.17.2) lib/enum.ex:4423: anonymous fn/3 in Enum.each/2
    (elixir 1.17.2) lib/stream.ex:1879: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir 1.17.2) lib/enum.ex:4858: Enumerable.List.reduce/3
    (elixir 1.17.2) lib/stream.ex:1027: Stream.do_transform_inner_list/7
    (elixir 1.17.2) lib/stream.ex:1891: Enumerable.Stream.do_each/4
```

Thanks for your help.

**Comment by micgerber** [comment]
@sidler92, as mentioned in #452 here is the error : 

```
11:41:48.504 pid=<0.94.0> [info] user already exists: %{"email" => "dagi@infofauna.ch", "first_name" => "", "institution_id" => nil, "last_name" => "", "password" => "Hm3&kE5f5?Bb", "roles" => ["admin"]}
11:41:48.871 pid=<0.94.0> [info] importing user: %{"email" => "dagi@scnat.ch", "first_name" => "", "institution_id" => nil, "last_name" => "", "password" => "&Ezi6RfkQRN5", "roles" => ["admin"]}
11:41:49.121 pid=<0.94.0> [info] importing user: %{"email" => "dagi@zebbra.ch", "first_name" => "", "institution_id" => nil, "last_name" => "", "password" => "eEirX9!j8?4K", "roles" => ["admin"]}
11:41:49.129 pid=<0.94.0> [error] could not import user: %{"email" => "alexis.beck@geneve.ch", "first_name" => "Alexis", "institution" => "MHNG", "last_name" => "Beck", "password" => "4JQKZz87Na", "roles" => "collection_digitizer"}, reason was: %RuntimeError{message: "GRSCICOLL_API_BASE_URL is not set"}
** (throw) %RuntimeError{message: "GRSCICOLL_API_BASE_URL is not set"}
    (data_aggregator 0.1.0) lib/data_aggregator/accounts/user_importer.ex:34: DataAggregator.Accounts.UserImporter.maybe_import_user_from_csv/1
    (elixir 1.17.2) lib/enum.ex:992: anonymous fn/3 in Enum.each/2
    (elixir 1.17.2) lib/enum.ex:4423: anonymous fn/3 in Enum.each/2
    (elixir 1.17.2) lib/stream.ex:1879: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir 1.17.2) lib/enum.ex:4858: Enumerable.List.reduce/3
    (elixir 1.17.2) lib/stream.ex:1027: Stream.do_transform_inner_list/7
    (elixir 1.17.2) lib/stream.ex:1891: Enumerable.Stream.do_each/4
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```
GRSCICOLL_API_BASE_URL is not set but what should be is value?

**Comment by micgerber** [comment]
@sidler92, 
I found the value under data_aggregator\config\.env.prod.
I'll try this and come back to you.

**Comment by micgerber** [comment]
@sidler92 the error is gone.
On info level, the institutions can't be found : 
```
11:58:27.882 pid=<0.94.0> [info] user already exists: %{"email" => "dagi@infofauna.ch", "first_name" => "", "institution_id" => nil, "last_name" => "", "password" => "Hm3&kE5f5?Bb", "roles" => ["admin"]}
11:58:27.885 pid=<0.94.0> [info] user already exists: %{"email" => "dagi@scnat.ch", "first_name" => "", "institution_id" => nil, "last_name" => "", "password" => "&Ezi6RfkQRN5", "roles" => ["admin"]}
11:58:27.888 pid=<0.94.0> [info] user already exists: %{"email" => "dagi@zebbra.ch", "first_name" => "", "institution_id" => nil, "last_name" => "", "password" => "eEirX9!j8?4K", "roles" => ["admin"]}
11:58:28.798 pid=<0.94.0> [info] importing user: %{"email" => "alexis.beck@geneve.ch", "first_name" => "Alexis", "institution_id" => "8d572607-d32c-4477-8834-c9dbe76c57f9", "last_name" => "Beck", "password" => "4JQKZz87Na", "roles" => ["collection_digitizer"]}
11:58:28.803 pid=<0.94.0> [info] could not find institution with code: NATUREUM
11:58:29.047 pid=<0.94.0> [info] importing user: %{"email" => "noemie.chervet@vd.ch", "first_name" => "Noémie", "institution_id" => nil, "last_name" => "Chervet", "password" => "4JQKZz87Na", "roles" => ["collection_digitizer"]}
11:58:29.051 pid=<0.94.0> [info] could not find institution with code: G
11:58:29.294 pid=<0.94.0> [info] importing user: %{"email" => "Anouk.Mentha@geneve.ch", "first_name" => "Anouk", "institution_id" => nil, "last_name" => "Mentha", "password" => "4JQKZz87Na", "roles" => ["collection_digitizer"]}
11:58:29.298 pid=<0.94.0> [info] could not find institution with code: NHMF
11:58:29.543 pid=<0.94.0> [info] importing user: %{"email" => "christian.puentener@fr.ch", "first_name" => "Christian", "institution_id" => nil, "last_name" => "Puentener", "password" => "4JQKZz87Na", "roles" => ["collection_digitizer"]}
11:58:29.793 pid=<0.94.0> [info] importing user: %{"email" => "katja.rembold@unibe.ch", "first_name" => "Katja", "institution_id" => "f6abc948-1068-4d23-b165-701e8734c07e", "last_name" => "Rembold", "password" => "4JQKZz87Na", "roles" => ["collection_digitizer"]}
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
```
Is it a problem?

**Comment by sidler92** [comment]
@micgerber yes. that is the right value for GRSCICOLL_API_BASE_URL for now.
And the Info logs you see there are not a problem, you can ignore them for now.

About the env variables like GRSCICOLL_API_BASE_URL:
We will create a list for you with all the env variables you have to set for your prod and int environment respectively.

**Comment by micgerber** [comment]
@sidler92 The aggregator is working again.
I'll be able to run some tests.
Thanks a lot for your help and thanks in advance for the list of env variables.
